# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
#  - board: nice_nano_v2
#    shield: chocofi_left nice_view_adapter nice_view
#  - board: nice_nano_v2
#    shield: chocofi_right nice_view_adapter nice_view
#  - board: nice_nano_v2
#    shield: settings_reset
#  - board: nice_nano_v2
#    shield: lily58_left nice_view_adapter nice_view
#  - board: nice_nano_v2
#    shield: lily58_right nice_view_adapter nice_view
# Hillside 46
#   Comment out below if you do not have this board, to save build time
  - board: nice_nano_v2
    shield: hillside46_left 
  - board: nice_nano_v2
    shield: hillside46_right 
