file_format: "1"
id: hillside46
name: Hillside46
type: shield
url: https://github.com/mmccoyd/hillside/
requires: [pro_micro]
features:
  - keys
  - encoder
  - underglow
siblings:
  - hillside46_left
  - hillside46_right